#!/bin/sh

set -e

echo "msfupdate is no longer supported when Metasploit is part of the operating
system. Checking for updates via the system package manager instead"
apt update && apt -y install metasploit-framework
